# Generated by Django 2.2.28 on 2023-01-16 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('ips', models.Field(default=[])),
                ('walletUserBTC', models.FloatField(default=0)),
                ('walletUserValueBTC', models.FloatField(default=0)),
                ('walletUserUSD', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderType', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], default='Buy', max_length=10)),
                ('orderStatus', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=10)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('priceOrder', models.FloatField(default=0)),
                ('profitOrder', models.FloatField(default=0)),
                ('quantity', models.FloatField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='listTransaction',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('price', models.FloatField(default=0)),
                ('quantity', models.FloatField(default=0)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='buyer', to='app.Profile')),
                ('buyerUser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='buyeruser', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='seller', to='app.Profile')),
                ('sellerUser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='selleruser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
